"""rename the 'full_name' column in user to 'name'

Revision ID: 067a23aab359
Revises: 9ee6b299e59a
Create Date: 2025-09-29 20:48:26.852517

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "067a23aab359"
down_revision: Union[str, Sequence[str], None] = "9ee6b299e59a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("name", sa.String(), nullable=False))
    op.drop_column("user", "full_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("full_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("user", "name")
    # ### end Alembic commands ###
