"""add created_at field in media_metadata table

Revision ID: 8202319e3f01
Revises: 673c97b98cea
Create Date: 2025-10-02 23:39:01.665912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8202319e3f01'
down_revision: Union[str, Sequence[str], None] = '673c97b98cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_metadata', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('media_metadata', 'caption',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_metadata', 'caption',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('media_metadata', 'created_at')
    # ### end Alembic commands ###
