"""remove video type and related columns

Revision ID: 95546785f29c
Revises: 2d88de201088
Create Date: 2025-10-16 22:31:11.229381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '95546785f29c'
down_revision: Union[str, Sequence[str], None] = '2d88de201088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'width')
    op.drop_column('media', 'duration')
    op.drop_column('media', 'height')
    op.alter_column('media_metadata', 'embeddings',
               existing_type=Vector(),
               nullable=False)
    op.drop_column('media_metadata', 'audio_tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_metadata', sa.Column('audio_tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.alter_column('media_metadata', 'embeddings',
               existing_type=Vector(),
               nullable=True)
    op.add_column('media', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('media', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('media', sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
