"""init

Revision ID: 9ee6b299e59a
Revises: 
Create Date: 2025-09-29 01:47:41.063992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '9ee6b299e59a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.Enum('IMAGE', 'AUDIO', 'VIDEO', 'TEXT', name='filetype'), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('storage_url', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('caption', sa.String(), nullable=False),
    sa.Column('ocr_text', sa.String(), nullable=True),
    sa.Column('transcript', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('topics', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('audio_tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('embeddings', Vector(), nullable=True),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_metadata')
    op.drop_table('media')
    op.drop_table('user')
    # ### end Alembic commands ###
