"""remove storage_url for media schema

Revision ID: afea5faa0c67
Revises: 3dab504c77a6
Create Date: 2025-10-23 21:50:02.636835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afea5faa0c67'
down_revision: Union[str, Sequence[str], None] = '3dab504c77a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'storage_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('storage_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
